# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rinchi-CPlusPlus-Preprocessor
version:      0.02
version_from: lib/Rinchi/CPlusPlus/Preprocessor.pm
installdirs:  site
requires:
    Carp:                          1.04
    Exporter:                      5.58
    XSLoader:                      0.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
